export default {
  HANAMURA: 'HANAMURA',
  HORIZONLUNARCOLONY: 'HORIZON LUNAR COLONY',
  TEMPLEOFANUBIS: 'TEMPLE OF ANUBIS',
  VOLSKAYAINDUSTRIES: 'VOLSKAYA INDUSTRIES',
  DORADO: 'DORADO',
  JUNKERTOWN: 'JUNKERTOWN',
  ROUTE66: 'ROUTE 66',
  'WATCHPOINT:GIBRALTAR': 'WATCHPOINT: GIBRALTAR',
  BLIZZARDWORLD: 'BLIZZARD WORLD',
  EICHENWALDE: 'EICHENWALDE',
  HOLLYWOOD: 'HOLLYWOOD',
  "KING'SROW": "KING'S ROW",
  NUMBANI: 'NUMBANI',
  ILIOS: 'ILIOS',
  LIJIANGTOWER: 'LIJIANG TOWER',
  NEPAL: 'NEPAL',
  OASIS: 'OASIS'
}
