export default [
  'HANAMURA',
  'HORIZON LUNAR COLONY',
  'TEMPLE OF ANUBIS',
  'VOLSKAYA INDUSTRIES',
  'DORADO',
  'JUNKERTOWN',
  'ROUTE 66',
  'WATCHPOINT: GIBRALTAR',
  'BLIZZARD WORLD',
  'EICHENWALDE',
  'HOLLYWOOD',
  "KING'S ROW",
  'NUMBANI',
  'ILIOS',
  'LIJIANG TOWER',
  'NEPAL',
  'OASIS'
]
